spring:
  application:
    name: Client Booking Backend
  batch:
    job:
      enabled: false
  logging:
    level:
      org:
        springframework:
          security: DEBUG
          springframework: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
  flyway:
    baseline-on-migrate: true
    defaultSchema: public
  config:
    import: secret.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

