spring:
  datasource:
    url: jdbc:h2:mem:testclientdb;NON_KEYWORDS=year
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
