spring:
  application:
    name: Client Booking Backend
  batch:
    job:
      enabled: false
  logging:
    level:
      org:
        springframework:
          data:
            redis: DEBUG
          security: DEBUG
          springframework: DEBUG
#        hibernate:
#          SQL: DEBUG
#          type:
#            descriptor:
#              sql:
#                BasicBinder: TRACE
        axonframework: DEBUG
  flyway:
    baseline-on-migrate: true
    defaultSchema: public
  config:
    import: secret.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 9091
retry:
  interval: 5
  maxCount: 3

otel:
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
#exporter:
#  otlp:
#    endpoint: http://localhost:4318
#    protocol: http/protobuf

