spring:
  application:
    name: Responder Assignment Backend
  logging:
    level:
      org:
        springframework:
          data:
            redis: DEBUG
          security: DEBUG
          springframework: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
  flyway:
    baseline-on-migrate: true
    defaultSchema: public
  config:
    import: secret.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9092

axon:
  axonserver:
    clientId: Responder Assignment Backend

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  metrics:
    exporter: none #this is to stop sending metrics, as it will fail, jaeger cannot handle metrics.
  logs:
    exporter: none #this is to stop sending logs, as it will fail, jaeger cannot handle logs.